import type { Metadata } from 'next/types';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from '../context/AuthProvider';
import { ArticleProvider } from '../context/ArticleProvider';
import { NotificationProvider } from '../context/NotificationProvider';
import SiteLayout from './components/layout';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <ArticleProvider>
            <NotificationProvider>
              <SiteLayout>
                {children}
              </SiteLayout>
            </NotificationProvider>
          </ArticleProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
